language: java
jdk:
  - oraclejdk8
  - oraclejdk9
# We need a dummy username/password property set even though we aren't publishing to sonatype
install: ./gradlew assemble -PossrhUsername=dummy -PossrhPassword=dummy
script: ./gradlew check -PossrhUsername=dummy -PossrhPassword=dummy
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/