package com.andrewjamesjohnson.junit;

import java.util.Collection;

/**
 * Interface for classes that generate parameters for parameterized test methods
 * The generated objects must implement {@link Parameter}
 *
 * @param <T> The type of {@code Parameter} generated by this class
 */
@FunctionalInterface
public interface ParameterGenerator<T extends Parameter> {
    /**
     * Generate parameters
     *
     * @return A {@code Collection} of {@code T} instances
     */
    Collection<T> generate();
}
